### ISSUE TITLE
feat: minecraft server packages

### ISSUE THREAD

**Issue by jyooru** [jyooru/nix-minecraft-servers#1]
- [ ] #18
- [x] #3
- [x] #16
- [x] #5
- [ ] [forge](https://forums.minecraftforge.net/)
- [ ] [fabric](https://fabricmc.net/use/server/)

**Comment by tomberek** [comment]
I can help test these if you'd like. Mods would be interesting to add to the framework.

**Comment by jyooru** [comment]
> I can help test these if you'd like.

That would be really useful!

> Mods would be interesting to add to the framework.

That's a good idea, we can look into it once I finish adding these servers.

**Comment by jyooru** [comment]
I've decided that I am going to stop maintaining this project, and will be archiving it shortly.
